#!/usr/bin/env python3
"""Generate the token data the write-up's inspector runs on.

The page lets a reader pick a compound and see how Qwen3-4B actually splits it,
with and without a leading space, next to the activation the feature gave it.
Those tokenizations are computed here rather than typed by hand, so the page
cannot drift from the tokenizer.

Activation values come from the committed reference run; only words that were
actually measured are included.

    python scripts/build_page_data.py
"""

from __future__ import annotations

import sys
from pathlib import Path

# Allow running straight from a clone, without `pip install -e .`
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import argparse  # noqa: E402
import json  # noqa: E402

from tokenization_awareness.config import PROJECT_ROOT  # noqa: E402
from tokenization_awareness.dataset import (  # noqa: E402
    build_groups,
    load_compounds,
    load_tokenizer,
    tokenize_both_ways,
)

# Words with a measured activation, from results/reference_run/nonzero_words.json
# plus the zero-activation words printed in the original run's head samples.
MEASURED: dict[str, float] = {
    # true single-token — fired
    "heartbeat": 20.25,
    "headline": 10.0,
    "copyright": 8.625,
    "breadcrumb": 8.0,
    "deadline": 7.4688,
    "weekday": 7.3438,
    "newsletter": 6.5,
    "dropout": 6.125,
    "thumbnail": 5.9688,
    "popover": 5.5312,
    "lifetime": 4.3438,
    "benchmark": 3.4688,
    "bookmark": 2.5312,
    "sandbox": 2.2031,
    "barcode": 1.6641,
    "passport": 0.0356,
    # true single-token — silent
    "airport": 0.0,
    "football": 0.0,
    "software": 0.0,
    "someone": 0.0,
    "another": 0.0,
    # conditional single-token
    "waterfall": 14.75,
    "lawsuit": 6.4375,
    "hindsight": 6.4375,
    "farewell": 5.6875,
    "downhill": 3.328125,
    "salesman": 1.1484375,
    "overpower": 0.0,
    "roadway": 0.0,
    "understand": 0.0,
    "countryside": 0.0,
    # true multi-token — fired
    "lighthouse": 9.125,
    "summertime": 7.5938,
    "peppermint": 6.3438,
    "lifeguard": 3.2812,
    "skyscraper": 2.2031,
    "oversleep": 1.9844,
    "jigsaw": 1.2031,
    "limelight": 0.6055,
    "humankind": 0.1855,
    # true multi-token — silent
    "flowerpot": 0.0,
    "snowfall": 0.0,
    "aftereffect": 0.0,
    "snowflake": 0.0,
    "flyby": 0.0,
}

#: Words the prose walks through, which the page should always offer.
FEATURED = ["firefighter", "newsletter", "sunflower"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=PROJECT_ROOT / "docs" / "assets" / "tokens.js",
        help="where to write the page data",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    tokenizer = load_tokenizer()
    groups = build_groups(tokenizer, load_compounds())
    group_of = {
        word: name for name, words in groups.as_dict().items() for word in words
    }

    entries = []
    for word in list(MEASURED) + [w for w in FEATURED if w not in MEASURED]:
        bare, spaced = tokenize_both_ways(tokenizer, word)
        entries.append(
            {
                "word": word,
                "group": group_of.get(word, "unlisted"),
                "bare": bare,
                "spaced": spaced,
                "activation": MEASURED.get(word),
            }
        )

    entries.sort(key=lambda e: (e["group"], -(e["activation"] or -1), e["word"]))

    payload = {
        "model": tokenizer.name_or_path,
        "feature": 118230,
        "layer": 0,
        "featured": FEATURED,
        "words": entries,
    }

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as handle:
        handle.write("// Generated by scripts/build_page_data.py — do not edit.\n")
        handle.write("window.TOKEN_DATA = ")
        json.dump(payload, handle, indent=2, ensure_ascii=False)
        handle.write(";\n")

    measured = sum(1 for e in entries if e["activation"] is not None)
    print(f"Wrote {args.output} — {len(entries)} words, {measured} with activations")


if __name__ == "__main__":
    main()
